name: Build wait-for-url

on:
  push:
    branches:
      - main
    paths:
      - 'wait-for-url/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./wait-for-url
          file: ./wait-for-url/Dockerfile
          platforms: linux/amd64
          push: true
          tags: aligor/wait-for-url
